---
title: "Ceteris Paribus Plots"
author: "Przemyslaw Biecek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Title of your vignette}
  %\usepackage[UTF-8]{inputenc}
---

# Introduction

First, let's create explainers for random Forest model and linear model

```{r, warning=FALSE, message=FALSE}
library("DALEX")
library("randomForest")
library("ceterisParibus")
set.seed(59)

apartments_lm_model <- lm(m2.price ~ construction.year + surface + floor + 
                            no.rooms + district, data = apartments)

apartments_rf_model <- randomForest(m2.price ~ construction.year + surface + floor + 
                                      no.rooms + district, data = apartments)

explainer_rf <- explain(apartments_rf_model, 
                        data = apartmentsTest[,2:6], y = apartmentsTest$m2.price)
explainer_lm <- explain(apartments_lm_model, 
                        data = apartmentsTest[,2:6], y = apartmentsTest$m2.price)
```

# Ceteris Paribus Plots

We will explain prediction for

```{r, fig.width=7, fig.height=7}
new_apartment <- apartmentsTest[1, ]
new_apartment

wi_rf <- ceteris_paribus(explainer_rf, observation = new_apartment)
wi_rf
plot(wi_rf, split = "variables", color = "variables", quantiles = FALSE)
plot(wi_rf, split = "variables", color = "variables")
plot(wi_rf)

wi_lm <- ceteris_paribus(explainer_lm, observation = new_apartment)
wi_lm
plot(wi_lm, split = "variables", color = "variables", quantiles = FALSE)
plot(wi_lm, split = "variables", color = "variables")
plot(wi_lm)

```

# Ceteris Paribus - two models

```{r, fig.width=7, fig.height=7}
plot(wi_rf, wi_lm, split = "variables", color = "models", quantiles = FALSE)
plot(wi_rf, wi_lm, split = "variables", color = "models")
plot(wi_rf, wi_lm)
```


# Interactive Ceteris Paribus Plots 

```{r, fig.width=7, fig.height=7, message=FALSE, warning=FALSE, eval=FALSE}
library("ggiraph")

plot_interactive(wi_rf, split = "variables", color = "variables")
plot_interactive(wi_rf)

plot_interactive(wi_lm, split = "variables", color = "variables")
plot_interactive(wi_lm)
```

# Interactive Ceteris Paribus Plots - two models

```{r, fig.width=7, fig.height=7, eval=FALSE}
plot_interactive(wi_rf, wi_lm)
plot_interactive(wi_rf, wi_lm, split = "variables")
```

